name: CI - Test Before Merge
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      - name: Run Tests
        run: ./gradlew test --no-daemon